@api = http://localhost:4002/api/users

### sign in
PUT {{api}}/632f65ba5b64be0231a09227
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmY2NWJhNWI2NGJlMDIzMWEwOTIyNyIsImlhdCI6MTY2NDA1MDYzNSwiZXhwIjoxNjY0MDY1MDM1fQ.n-w6eIXFfOoH6F8sbBS-4PaNQB5zYVu2HtACdtnB-DE

{
    "email": "",
    "username": "",
    "password": "",
    "image": "https://www.esimagenes.com/pimagen/squirtle-pokemon.png",
    "firstName" : "Sebastian",
    "lastName" : "Garcia"
}